services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-34l)ez5cw)=9c_^8h*)&8%nyv&ghsjhux*hjwn%*brb%3#eg&k
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: taskman-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: taskman-db
          property: connectionString
    autoDeploy: true
